### ISSUE TITLE
dont know how to install

### ISSUE THREAD

**Issue by ChristopherDrewesIU** [Freemanium/govee_btled#1]
i did the pip install -U git+https://github.com/Freemanium/govee_btled but dont know how to go on... can you pls help me?

**Comment by chvolkmann** [comment]
1) Install the package into your environment using 
    ```bash
    pip install -U git+https://github.com/Freemanium/govee_btled
    ```
2) Write a Python script that utilizes the package, e.g.
    ```python3
    from govee_btled import BluetoothLED
    led = BluetoothLED('<your MAC here>')
    led.set_state(True)
    led.set_color('blue')
    ```
