### ISSUE TITLE
gatttol don't exists anymore

### ISSUE THREAD

**Issue by qawsedrftgzh** [Freemanium/govee_btled#5]
Well while running it on manjaro linux it says that the command "gatttol" was no found the gatttol command is not in the official repos neither in the AUR

**Comment by qawsedrftgzh** [comment]
But it works fine on Kubuntu

**Comment by chvolkmann** [comment]
First Google result: https://wiki.archlinux.org/index.php/Bluetooth

> **Deprecated BlueZ tools**
> Eight BlueZ tools were deprecated and removed from bluez-utils, although not all of them were superseded by newer tools. The **bluez-utils-compat** package provides an alternative version of bluez-utils with the deprecated tools.

https://aur.archlinux.org/packages/bluez-utils-compat/
